# Generated by Django 4.2.6 on 2023-10-10 03:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossyroad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
