# Generated by Django 4.2.6 on 2023-10-12 05:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'cctv',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CrosswalkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('traffic', models.BooleanField()),
                ('cctv', models.IntegerField()),
                ('distance_to_cctv', models.FloatField()),
            ],
            options={
                'db_table': 'crosswalk',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrafficModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'traffic',
                'ordering': ['id'],
            },
        ),
    ]
