# Generated by Django 4.2.6 on 2023-10-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctvmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='crosswalkmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='trafficmodel',
            options={'ordering': ['-id']},
        ),
    ]
